version: "3.3"

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:80  shop.wsgi
    ports:
      - 80:80


#  nginx:
#    build: ./nginx
#    depends_on:
#      - web
#    ports:
#      - 80:80
#    links:
#      - web
