version: "3.3"

services:
  web:
    container_name: web
    build: .
    command: gunicorn --bind 0.0.0.0:8000  shop.wsgi:application
    volumes:
      - ./static:/static
      - ./media:/media
    expose:
      - 8000
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=django_shop

  nginx:
    container_name: nginx
    build: ./nginx
    #    image: nginx:latest
#    volumes:
#      - ./nginx:/etc/nginx/conf.d
    volumes:
      - ./static:/static
      - ./media:/media
    depends_on:
      - web
    ports:
      - 80:80

volumes:
  postgres_data:

